apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-qkif
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-qkif
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-qkif
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-qkif
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-qkif
    spec:
      containers:
      - image: quay.io/rh-gitops-bot/rhtap-demo-logr-tenant/rhtap-demo-app/hacbs-test-project-qkif@sha256:0bc862faee2d2319069bb50749a9f782c0a6f0422925a25479bb32cef334ee32
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
